"""following the naming conventions to make class names singular instead of plural

Revision ID: c16d751fb944
Revises: 444e50d160ec
Create Date: 2022-05-03 14:14:31.001677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16d751fb944'
down_revision = '444e50d160ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
